# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:title
exclude: ["node_modules", "vendor"]
include: ["_pages"]
sass:
  style: compressed

# Site info
url: http://silentpost.co
title: Software design and development from silentpost
